- name: Install Redis repos
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install redis
  yum:
    name: redis
    state: present
    enablerepo: remi
