- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Download Artifacts
  include_role:
    name: common
    tasks_from: artifact-download
  vars:
    APP_NAME: frontend

- name: Remove old htdocs
  file:
    path: /usr/share/nginx/html
    state: absent

- name: Copy Htdocs
  copy:
    src: /tmp/frontend/static
    dest: /usr/share/nginx/html



