- name: Setup MongoDB yum repo
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: latest

- name: Start Service MongoDB
  systemd:
    state: started
    name: mongod
    enabled: yes

- name: Download Artifacts
  include_role:
    name: common
    tasks_from: artifact-download
  vars:
    APP_NAME: mongo

- name: Load Schema
  shell: mongo </tmp/mongo/{{item}}
  loop:
    - catalogue.js
    - users.js


