- name: Download MySQL
  unarchive:
    src: "{{MYSQL_URL}}"
    dest: /tmp
    remote_src: yes

- name: Remove MariaDB
  yum:
    name: mariadb-libs
    state: absent


- name: Install MySQL
  yum:
    package: /tmp/{{item}}
    state: present
  loop:
    - mysql-community-client-5.7.28-1.el7.x86_64.rpm
    - mysql-community-common-5.7.28-1.el7.x86_64.rpm
    - mysql-community-libs-5.7.28-1.el7.x86_64.rpm
    - mysql-community-server-5.7.28-1.el7.x86_64.rpm


