- name: Check Package Installed
  yum:
    list: mysql-community-server
  register: out

- name: Download MySQL
  unarchive:
    src: "{{MYSQL_URL}}"
    dest: /tmp
    remote_src: yes
  when: out.results|length == 0

- name: Remove MariaDB
  yum:
    name: mariadb-libs
    state: absent

- name: Install MySQL
  yum:
    name: /tmp/{{item}}
    state: present
  loop:
    - mysql-community-common-5.7.28-1.el7.x86_64.rpm
    - mysql-community-libs-5.7.28-1.el7.x86_64.rpm
    - mysql-community-client-5.7.28-1.el7.x86_64.rpm
    - mysql-community-server-5.7.28-1.el7.x86_64.rpm

- name: Start MySQL
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Grab Default Root Password
  shell: grep 'A temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: out

- name: Copy SQL file
  template:
    src: password-reset.sql
    dest: /root/.password-reset.sql

- name: Reset MySQL Password
  shell: mysql --connect-expired-password -uroot -p{{out.stdout}} </root/.password-reset.sql ; sed -e '/temporary/ d' /var/log/mysqld.log
  when: out.stdout == ""
