- name: Add Application User
  include_role:
    name: common
    tasks_from: application-user

- name: Download Artifacts
  include_role:
    name: common
    tasks_from: artifact-download
  vars:
    APP_NAME: catalogue

- name: Copy Artifacts
  copy:
    src: /tmp/catalogue
    dest: /home/{{APPLICATION_USER}}
    remote_src: yes

