- name: Get NodeJS Latest URL
  shell: curl -s https://nodejs.org/en/download/ | xargs -n1 | grep linux-x64.tar | sed -e 's|=| |g' -e 's|>| |g'| xargs -n1 | grep ^http
  register: out

- name: Download NodeJS
  unarchive:
    src: "{{out.stdout}}"
    dest: /opt
    remote_src: yes

- name: Get NodeJS Directory
  set_fact:
    NODEJS_DIR: "/opt/{{ out.stdout.split('/') | last | replace('.tar.xz','')}}"

- name: Create Command Links
  file:
    src: "{{NODEJS_DIR}}/bin/{{item}}"
    dest: "/bin/{{item}}"
    state: link
  loop:
    - node
    - npm
    - npx

