- name: Get NodeJS Latest URL
  shell: curl -s https://nodejs.org/en/download/ | xargs -n1 | grep linux-x64.tar | sed -e 's|=| |g' -e 's|>| |g'| xargs -n1 | grep ^http
  register: out

- name: Download NodeJS
  unarchive:
    src: "{{out.stdout}}"
    dest: /opt
    remote_src: yes

- name: Get NodeJS Directory
  set_fact:
    NODEJS_DIR: "{{ out.stdout.split('/') | last | replace('.tar.xz','')}}"

- name: debug
  debug:
    msg: "{{NODEJS_DIR}}"