- name: Copy AZ Repo
  template:
    src: azure-cli.repo
    dest: /etc/yum.repos.d/az.repo

- name: Install Azure Cli
  yum:
    name: azure-cli
    state: present
    disable_gpg_check: yes

- name: Install Azure DevOps Extension
  shell: az extension add --name azure-devops

- name: denug
  debug:
    msg: "{{AZ_LOGIN_DOWNLOAD_ARTIFACT}}"