- name: Copy AZ Repo
  template:
    src: azure-cli.repo
    dest: /etc/yum.repos.d/az.repo

- name: Install MicroSoft Packages Repos
  yum:
    name: https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
    state: present

- name: Install Azure Cli
  yum:
    name: [ "azure-cli", "libunwind", "libicu" ]
    state: present
    disable_gpg_check: yes

- name: Install Azure DevOps Extension
  shell: az extension add --name azure-devops

- name: Login to AZ DevOps
  shell: echo {{AZ_LOGIN_DOWNLOAD_ARTIFACT}} | az devops login --organization https://dev.azure.com/DevOps-Batches/

-