- name: Copy AZ Repo
  template:
    src: azure-cli.repo
    dest: /etc/yum.repos.d/az.repo

- name: Install MicroSoft Packages Repos
  yum:
    name: https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
    state: present

- name: Install Azure Cli
  yum:
    name: [ "azure-cli", "libunwind", "libicu" ]
    state: present
    disable_gpg_check: yes

- name: Install Azure DevOps Extension
  shell: az extension add --name azure-devops

- name: Login to AZ DevOps
  shell: echo {{AZ_LOGIN_DOWNLOAD_ARTIFACT}} | az devops login --organization https://dev.azure.com/DevOps-Batches/

- name: Stop Service If Running
  systemd:
    name: "{{APP_NAME}}"
    state: stopped
  ignore_errors: yes

- name: CleanUp old artifacts
  file:
    path: /home/{{APPLICATION_USER}}/{{APP_NAME}}
    state: absent

- name: Download Artifacts
  shell: rm -rf /tmp/{{APP_NAME}} ; mkdir /tmp/{{APP_NAME}} ; cd /tmp/{{APP_NAME}}; az artifacts universal download   --organization "{{ORG_URL}}" --project "{{PROJECT}}" --scope project --feed "RoboShop"   --name "{{APP_NAME}}" --version "{{APP_VERSION}}" --path .