- name: Add Application User
  include: application-user.yml

- name: Download Artifacts
  include: artifact-download.yml

- name: Copy Artifacts
  copy:
    src: /tmp/{{APP_NAME}}
    dest: /home/{{APPLICATION_USER}}
    remote_src: yes
    owner: "{{APPLICATION_USER}}"
    group: "{{APPLICATION_USER}}"

- name: Install NodeJS
  include: install/nodejs.yml

- name: Configure SystemD Service
  template:
    src: systemd.service
    dest: /etc/systemd/system/{{APP_NAME}}.service
  vars:
    COMMAND: "/bin/node /home/{{APPLICATION_USER}}/{{APP_NAME}}/server.js"

- name: Start Service
  systemd:
    name: "{{APP_NAME}}"
    state: restarted
    enabled: yes
