- name: Add Application User
  include: application-user.yml

- name: Download Artifacts
  include: artifact-download.yml

- name: Copy Artifacts
  copy:
    src: /tmp/{{APP_NAME}}
    dest: /home/{{APPLICATION_USER}}
    remote_src: yes
    owner: "{{APPLICATION_USER}}"
    group: "{{APPLICATION_USER}}"

- name: Install Python
  include: install/python.yml

- name: Install python deps
  pip:
    requirements: /home/{{APPLICATION_USER}}/{{APP_NAME}}/requirements.txt
    executable: pip3
    extra_args: --user

- name: Configure SystemD Service
  template:
    src: systemd.service
    dest: /etc/systemd/system/{{APP_NAME}}.service
  vars:
    COMMAND: "/usr/local/bin/uwsgi --ini payment.ini"
    WORKINGDIRECTORY: true

- name: Get UID
  shell: id -u {{APPLICATION_USER}}
  register: uid

- name: Get GID
  shell: id -g {{APPLICATION_USER}}
  register: gid

- name: Replace UID for Payment Service
  lineinfile:
    path: /home/{{APPLICATION_USER}}/{{APP_NAME}}/payment.ini
    regexp: '^uid'
    line: 'uid = {{uid.stdout}}'
    backrefs: yes

- name: Replace GID for Payment Service
  lineinfile:
    path: /home/{{APPLICATION_USER}}/{{APP_NAME}}/payment.ini
    regexp: '^gid'
    line: 'gid = {{gid.stdout}}'
    backrefs: yes


- name: Start Service
  systemd:
    name: "{{APP_NAME}}"
    state: restarted
    enabled: yes
