- name: Add Application User
  include: application-user.yml

- name: Download Artifacts
  include: artifact-download.yml

- name: Copy Artifacts
  copy:
    src: /tmp/{{APP_NAME}}
    dest: /home/{{APPLICATION_USER}}
    remote_src: yes
    owner: "{{APPLICATION_USER}}"
    group: "{{APPLICATION_USER}}"

- name: Install Python
  include: install/python.yml

- name: Install python deps
  pip:
    requirements: /home/{{APPLICATION_USER}}/{{APP_NAME}}/requirements.txt
    executable: pip3
  become_user: "{{APPLICATION_USER}}"

- name: Configure SystemD Service
  template:
    src: systemd.service
    dest: /etc/systemd/system/{{APP_NAME}}.service
  vars:
    COMMAND: "/usr/local/bin/uwsgi --ini payment.ini"
    APPLICATION_USER: root

#- name: Start Service
#  systemd:
#    name: "{{APP_NAME}}"
#    state: restarted
#    enabled: yes
